### ISSUE TITLE
Requests não estão funcionando

### ISSUE THREAD

**Issue by felipecastilhos** [jradesenv/sef-mock#1]
Bom dia, Jean!

Agradeço o esforço para ajudar o crescimento da comunidade do SEF, porém quando realizo as requisições de acordo com a documentação o serviço me informa que não há documento disponível.

Abraço

**Comment by jradesenv** [comment]
Bom dia, Felipe
Poderia me informar quais requests não estao funcionando?

**Comment by felipecastilhos** [comment]
Vejo que já corrigiu, agradeço a atenção!

**Comment by jradesenv** [comment]
Nao pode ser corrigido o que nao está errado. Colar de beijos.
